### PR TITLE
Major changes and clean up

### LINKED ISSUE #54: Capturing payment through spree admin fails (works on paypal)
Processing my first test orders, using both providors:
Spree::BillingIntegration::PaypalExpress
Spree::BillingIntegration::PaypalExpressUk

Order processes fine, customer returned to spree confirmation page.

Using the 'capture' button in spree admin, error displayed:

```
ArgumentError in Spree::Admin::PaymentsController#fire

wrong number of arguments (3 for 1)
Rails.root: /Users/steve/Documents/ruby/rkbbspree

Application Trace | Framework Trace | Full Trace
activesupport (3.2.2) lib/active_support/core_ext/kernel/reporting.rb:68:in `capture'
```

However, the payment can be accepted through the paypal interface and solving this is probably beyond my coding ability right now.
If it's working for others, perhaps this is to do with the currency being in GBP but the Sandbox dev account is USD (I don't recall the option to change). When accepting the payment through paypal I had to decide whether to keep in GBP or currency convert to USD.

### LINKED ISSUE #63: Promotions don't go through to paypal
When you are on the payment page and enter a promotion, then check out with paypal, the promotion is not showing up in the paypal price. This is on Spree 1.0

### PR DESCRIPTION
**Pull request by sbounmy**
My branch name is called 'custom' because my first intention was to make spree_store_credits compatible with spree_paypal_express, but I end up fixing a lot of features and though it would be great if this get merged into spree's repo:
- fixed capture and credit from /admin broken by spree 1.1 payment processing changes (fixes #54)
- paypal_confirm page displays the same page as order_confirm
- order.completed_at is now set on paypal_finish
- on checkout with paypal, order is automatically updated so promotions, coupons are computed before we land on paypal's page (fixes #63)
- cleaned up dependencies
- we consume user's store_credits if spree_store_credits is defined

The spec coverage is not as good as it should be, but I tried to add some spec and setup integrations test if anyone wants to help with.
This PR is actually tested with preferred_review set to true and deployed on production, but would love any feedback.

### CODE REVIEW

File: app/controllers/spree/checkout_controller_decorator.rb [hunk 1]
```diff
@@ -145,8 +147,15 @@ def paypal_finish
           Rails.logger.error ppx_auth_response.to_yaml
         end
 
-        @order.update_attribute(:state, "complete")
```
Comment (sbounmy) [inline app/controllers/spree/checkout_controller_decorator.rb:148]: @radar any idea why we are not using @order.complete! to preserve order's state callbacks ?

Comment (radar) [inline app/controllers/spree/checkout_controller_decorator.rb:148]: There are some state events triggered when this method is called, and those fail. Therefore we set this manually.
